version: '3'
services:
  public:
    container_name: toxicity_front
    image: lcs95/toxicity_monitor_frontend
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: 'unless-stopped'
    networks:
      - web
    depends_on:
      - api
  api:
    container_name: toxicity_api
    image: lcs95/toxicity_monitor:latest
    ports:
      - "5000:5000"
    networks:
      - web

networks:
  web:
    driver: bridge