version: '3'
services:
  public:
    container_name: toxicity_front
    image: lcs95/toxicity_monitor_frontend
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: 'unless-stopped'
    networks:
      - web
    depends_on:
      - api
  api:
    container_name: toxicity_api
    image: alexisnorindrefrei/toxicity_monitor
    ports:
      - "5000:5000"
    networks:
      - web
  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager
    restart: unless-stopped
    volumes:
      - "./alertmanager:/etc/alertmanager"
    ports:
      - 9093:9093
    networks:
      - web
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - 9090:9090
    depends_on:
      - api
      - alertmanager
      - node-exporter
      - cadvisor
    networks:
      - web
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - web
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - web
  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    command: '--port=8082'
    ports:
      - 8082:8082
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      # linux
      #- /var/lib/docker/:/var/lib/docker:ro
      # windows wsl
      - /mnt/windows_docker/:/rootfs/var/lib/docker:ro
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  grafana_data: {}