{
 "title": "Hardware and software metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "API container memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"toxicity_api\"}"
    }
   ]
  },
  {
   "title": "API container CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"toxicity_api\"}[1m])"
    }
   ]
  },
  {
   "title": "Host memory left",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100"
    }
   ]
  },
  {
   "title": "Host CPU load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "100 - ((rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) * 100)"
    }
   ]
  },
  {
   "title": "Host disk space left",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes/node_filesystem_size_bytes * 100)"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "toxicity_api_requests_total" }
   ]
  },
  {
   "title": "Exceptions over requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(toxicity_api_exceptions_total[1m]) / rate(toxicity_api_requests_total[1m])",
     "legendFormat": "exception over requests"
    }
   ]
  },
  {
   "title": "Average request reponse latency over last minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(toxicity_api_latency_seconds_sum[1m])/rate(toxicity_api_latency_seconds_count[1m])"
    }
   ]
  }
 ]
}